version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ycil-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ycil
    ports:
      - "51213:5432"
    volumes:
      - ycil-pgdata:/var/lib/postgresql/data

volumes:
  ycil-pgdata:
