version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ycil-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-ycil}
    ports:
      - "127.0.0.1:51213:5432"
    volumes:
      - ycil-pgdata:/var/lib/postgresql/data

volumes:
  ycil-pgdata:
